version: '3.8'
services:
  web:
    image: php:8.1-apache
    volumes:
      - ./app:/var/www/html
    hostname: web
    environment:
      - VIRTUAL_HOST="alumno3.infenlaces.com"
    depends_on:
      - mysql
  mysql:
    image: mysql
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=manuel
      - MYSQL_PASSWORD=manuel
      - MYSQL_DATABASE=roles
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
